// sidecar shadow [plan|remove] — mirror sidecar's OWN plugin commands into the
// user-scope command dir (~/.claude/commands/) as BARE `/cmd` delegators.
//
// Why: Claude Code namespaces plugin commands as `/plugin:cmd`. To get the bare
// `/cmd` form (what users actually type — `/arxiv`, `/dojo`, …) a user-scope
// `~/.claude/commands/<name>.md` must exist. The retired `sidecar` package did
// this with its own `shadow`; this is the sidecar-native, sidecar-free replacement
// so the bare-command layer is REGENERABLE and always points at `sidecar <cmd>`
// (never a dead `$CLAUDE_PLUGIN_ROOT`/sidecar-cache path again).
//
// Each generated file carries a MARKER (`SHADOW_MARKER`) so `remove` only ever
// deletes sidecar-generated shadows — a hand-authored user command of the same
// name is never clobbered (refresh skips it and warns). `--force` overrides the
// skip and overwrites EVERY collision from source — the one-shot heal for
// pre-marker shadows (generated before SHADOW_MARKER existed, so detected as
// "hand-authored" false-positives and left stale, often missing the current
// description's `Triggers —` line → the bare command stops being auto-recognized).
//
// @convergence state=ossified id=SHADOW_PREMARKER_STALE value="pre-marker shadows in ~/.claude/commands/ lack SHADOW_MARKER, so refresh skips them as 'hand-authored' and they go stale — 18/22 lost the source description's `Triggers —` line, so bare-text recognition of /fleet /sbs /easy … silently broke even though source commands/*.md were correct" threshold="resolved: `sidecar shadow --force` overwrites marker-less collisions from source (source = SSOT); run it once per host to heal pre-marker shadows. Re-breaks only if a NEW marker-less shadow layer is introduced without a heal path"
//
// @convergence state=ossified id=SHADOW_GEN_NATIVE value="bare /cmd shadows are generated by `sidecar shadow` from sidecar's own commands/ — not by the retired sidecar package, and never baked to a $CLAUDE_PLUGIN_ROOT/sidecar-cache path" threshold="a session's /arxiv etc. died because sidecar-generated shadows pointed at a removed ~/.claude/plugins/cache/sidecar path; sidecar now owns shadow generation, marker-tracked + regenerable"
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { homedir } from "node:os";
import { SIDECAR_ROOT } from "../lib/paths.ts";
import { info, ok, warn } from "../lib/log.ts";

const SHADOW_MARKER = "<!-- sidecar-shadow: generated by `sidecar shadow` · do not edit · regenerate/remove with `sidecar shadow` / `sidecar shadow remove` -->";

// @convergence state=ossified id=SHADOW_MARKER_AFTER_FRONTMATTER value="the SHADOW_MARKER must be inserted AFTER the YAML frontmatter block, never prepended — Claude Code only parses `description:` when `---` is on line 1; a marker on line 1 pushed frontmatter down so the picker rendered the marker comment as the command's description" threshold="if the marker is ever prepended again, every shadow command shows '<!-- sidecar-shadow ... -->' instead of its description in the slash picker"
// Insert the tracking marker so the frontmatter stays on line 1 (so the picker
// reads `description:`). Files open with a `---`…`---` frontmatter fence; drop the
// marker right after the closing fence. No frontmatter → prepend (harmless).
function withMarker(body: string): string {
  const lines = body.split("\n");
  if (lines[0] === "---") {
    const close = lines.indexOf("---", 1);
    if (close !== -1) {
      lines.splice(close + 1, 0, SHADOW_MARKER);
      return lines.join("\n");
    }
  }
  return `${SHADOW_MARKER}\n${body}`;
}
const SRC_DIR = resolve(SIDECAR_ROOT, "commands");
const DEST_DIR = resolve(homedir(), ".claude", "commands");

function isSidecarShadow(path: string): boolean {
  try {
    return readFileSync(path, "utf8").includes(SHADOW_MARKER);
  } catch {
    return false;
  }
}

// Source command files = sidecar's own commands/*.md (the plugin command set).
function sourceCommands(): string[] {
  if (!existsSync(SRC_DIR)) return [];
  return readdirSync(SRC_DIR).filter((f) => f.endsWith(".md")).sort();
}

// Description-recognition hygiene (sidecar `skill-desc-guard` @D s18, ported to
// sidecar commands/*.md). A bare /cmd is auto-recognized from natural language
// ONLY while its frontmatter `description:` survives Claude Code's skill-listing
// budget AND carries a `Triggers —` clause. Over the per-entry cap the entry is
// truncated/dropped (recognition silently dies); with no Triggers clause the
// model has to guess. warn-only (discoverability, not correctness). Active only
// in the sidecar repo itself (where commands/ exists).
const DESC_CAP = 1400; // Claude Code per-entry skill-listing cap (sidecar s18)
export function lintCommandDescriptions(): { rule: string; file: string; msg: string }[] {
  const issues: { rule: string; file: string; msg: string }[] = [];
  if (!existsSync(SRC_DIR)) return issues;
  for (const f of sourceCommands()) {
    const name = f.replace(/\.md$/, "");
    const txt = readFileSync(resolve(SRC_DIR, f), "utf8");
    const m = txt.match(/^description:\s*(.*)$/m);
    if (!m) {
      issues.push({ rule: "SHADOW-DESC", file: `commands/${f}`, msg: "no frontmatter `description:`" });
      continue;
    }
    const desc = m[1].trim().replace(/^["']|["']$/g, "");
    if (desc.length > DESC_CAP) {
      issues.push({ rule: "SHADOW-DESC", file: `commands/${f}`, msg: `description ${desc.length} > ${DESC_CAP}-char skill-listing cap — /${name} gets truncated/dropped from the listing (recognition dies)` });
    }
    if (!/Triggers|트리거/.test(desc)) {
      issues.push({ rule: "SHADOW-DESC", file: `commands/${f}`, msg: `description has no \`Triggers —\` clause — bare-text /${name} relies on the model guessing` });
    }
  }
  return issues;
}

// Write-time variant of the s18 rule (PreToolUse, content not yet on disk) — for
// any */commands/*.md or */SKILL.md with frontmatter `description:`. Mirrors
// sidecar `skill-desc-guard`: over-cap is an objective Claude Code limit → caller
// hard-DENIES; missing Triggers is sidecar opinion → caller WARNS. Returns the
// reason strings; null fields = clean. Path-scoped by the caller.
export function descWriteViolation(filePath: string, content: string): { block?: string; warn?: string } | null {
  const isCmd = /(^|\/)commands\/[^/]+\.md$/.test(filePath) || /(^|\/)SKILL\.md$/.test(filePath);
  if (!isCmd) return null;
  const m = content.match(/^description:\s*(.*)$/m);
  if (!m) return null; // no description: → not a recognizable command/skill entry
  const desc = m[1].trim().replace(/^["']|["']$/g, "");
  const out: { block?: string; warn?: string } = {};
  if (desc.length > DESC_CAP) {
    out.block = `description is ${desc.length} chars, ${desc.length - DESC_CAP} over the ${DESC_CAP}-char Claude Code skill-listing cap — over the cap this entry gets truncated/dropped from the listing and the model stops auto-recognizing it. Shrink it: lead with the trigger + the one verb it does; move flag tables / sub-verb catalogues into the body or \`--help\`.`;
  }
  if (!/Triggers|트리거/.test(desc)) {
    out.warn = `description has no \`Triggers —\` clause — bare-text recognition of this command relies on the model guessing. Append \`Triggers — "…", "…"\` (KO+EN phrases the user would actually type).`;
  }
  return out.block || out.warn ? out : null;
}

export function runShadow(args: string[]): number {
  const force = args.includes("--force");
  const verb = args.find((a) => !a.startsWith("--")) ?? "apply";

  if (verb === "remove" || verb === "unshadow") {
    if (!existsSync(DEST_DIR)) {
      info("shadow remove: no ~/.claude/commands — nothing to remove");
      return 0;
    }
    let removed = 0;
    for (const f of readdirSync(DEST_DIR).filter((f) => f.endsWith(".md"))) {
      const p = resolve(DEST_DIR, f);
      if (isSidecarShadow(p)) {
        rmSync(p);
        removed++;
      }
    }
    ok(`shadow remove: deleted ${removed} sidecar-generated bare command(s)`);
    return 0;
  }

  const src = sourceCommands();
  if (src.length === 0) {
    warn(`shadow: no source commands at ${SRC_DIR}`);
    return 1;
  }
  const plan = verb === "plan";
  if (!plan) mkdirSync(DEST_DIR, { recursive: true });

  let written = 0;
  let forced = 0;
  let skipped = 0;
  const skippedNames: string[] = [];
  const forcedNames: string[] = [];
  for (const f of src) {
    const destPath = resolve(DEST_DIR, f);
    const collides = existsSync(destPath) && !isSidecarShadow(destPath);
    // never clobber a hand-authored (non-sidecar-shadow) user command of the same
    // name — UNLESS --force (one-shot heal for pre-marker stale shadows; source=SSOT).
    if (collides && !force) {
      skipped++;
      skippedNames.push(f.replace(/\.md$/, ""));
      continue;
    }
    if (collides && force) {
      forced++;
      forcedNames.push(f.replace(/\.md$/, ""));
    }
    if (!plan) {
      const body = readFileSync(resolve(SRC_DIR, f), "utf8").replace(/\n+$/, "");
      writeFileSync(destPath, withMarker(body) + "\n");
    }
    written++;
  }

  const tag = plan ? "shadow plan (dry-run)" : "shadow";
  ok(`${tag}: ${plan ? "would write" : "wrote"} ${written} bare /cmd → ${DEST_DIR}`);
  if (forced) warn(`  --force overwrote ${forced} marker-less collision(s) from source: ${forcedNames.join(" · ")}`);
  if (skipped) warn(`  skipped ${skipped} (hand-authored, not overwritten — \`shadow --force\` to overwrite from source): ${skippedNames.join(" · ")}`);
  if (!plan) info("  reload Claude Code (/reload-plugins or restart) to pick up the bare commands");
  return 0;
}
