// harness shadow [plan|remove] — mirror harness's OWN plugin commands into the
// user-scope command dir (~/.claude/commands/) as BARE `/cmd` delegators.
//
// Why: Claude Code namespaces plugin commands as `/plugin:cmd`. To get the bare
// `/cmd` form (what users actually type — `/arxiv`, `/dojo`, …) a user-scope
// `~/.claude/commands/<name>.md` must exist. The retired `sidecar` package did
// this with its own `shadow`; this is the harness-native, sidecar-free replacement
// so the bare-command layer is REGENERABLE and always points at `harness <cmd>`
// (never a dead `$CLAUDE_PLUGIN_ROOT`/sidecar-cache path again).
//
// Each generated file carries a MARKER (`SHADOW_MARKER`) so `remove` only ever
// deletes harness-generated shadows — a hand-authored user command of the same
// name is never clobbered (refresh skips it and warns).
//
// @convergence state=ossified id=SHADOW_GEN_NATIVE value="bare /cmd shadows are generated by `harness shadow` from harness's own commands/ — not by the retired sidecar package, and never baked to a $CLAUDE_PLUGIN_ROOT/sidecar-cache path" threshold="a session's /arxiv etc. died because sidecar-generated shadows pointed at a removed ~/.claude/plugins/cache/sidecar path; harness now owns shadow generation, marker-tracked + regenerable"
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { homedir } from "node:os";
import { HARNESS_ROOT } from "../lib/paths.ts";
import { info, ok, warn } from "../lib/log.ts";

const SHADOW_MARKER = "<!-- harness-shadow: generated by `harness shadow` · do not edit · regenerate/remove with `harness shadow` / `harness shadow remove` -->";

// @convergence state=ossified id=SHADOW_MARKER_AFTER_FRONTMATTER value="the SHADOW_MARKER must be inserted AFTER the YAML frontmatter block, never prepended — Claude Code only parses `description:` when `---` is on line 1; a marker on line 1 pushed frontmatter down so the picker rendered the marker comment as the command's description" threshold="if the marker is ever prepended again, every shadow command shows '<!-- harness-shadow ... -->' instead of its description in the slash picker"
// Insert the tracking marker so the frontmatter stays on line 1 (so the picker
// reads `description:`). Files open with a `---`…`---` frontmatter fence; drop the
// marker right after the closing fence. No frontmatter → prepend (harmless).
function withMarker(body: string): string {
  const lines = body.split("\n");
  if (lines[0] === "---") {
    const close = lines.indexOf("---", 1);
    if (close !== -1) {
      lines.splice(close + 1, 0, SHADOW_MARKER);
      return lines.join("\n");
    }
  }
  return `${SHADOW_MARKER}\n${body}`;
}
const SRC_DIR = resolve(HARNESS_ROOT, "commands");
const DEST_DIR = resolve(homedir(), ".claude", "commands");

function isHarnessShadow(path: string): boolean {
  try {
    return readFileSync(path, "utf8").includes(SHADOW_MARKER);
  } catch {
    return false;
  }
}

// Source command files = harness's own commands/*.md (the plugin command set).
function sourceCommands(): string[] {
  if (!existsSync(SRC_DIR)) return [];
  return readdirSync(SRC_DIR).filter((f) => f.endsWith(".md")).sort();
}

export function runShadow(args: string[]): number {
  const verb = args[0] ?? "apply";

  if (verb === "remove" || verb === "unshadow") {
    if (!existsSync(DEST_DIR)) {
      info("shadow remove: no ~/.claude/commands — nothing to remove");
      return 0;
    }
    let removed = 0;
    for (const f of readdirSync(DEST_DIR).filter((f) => f.endsWith(".md"))) {
      const p = resolve(DEST_DIR, f);
      if (isHarnessShadow(p)) {
        rmSync(p);
        removed++;
      }
    }
    ok(`shadow remove: deleted ${removed} harness-generated bare command(s)`);
    return 0;
  }

  const src = sourceCommands();
  if (src.length === 0) {
    warn(`shadow: no source commands at ${SRC_DIR}`);
    return 1;
  }
  const plan = verb === "plan";
  if (!plan) mkdirSync(DEST_DIR, { recursive: true });

  let written = 0;
  let skipped = 0;
  const skippedNames: string[] = [];
  for (const f of src) {
    const destPath = resolve(DEST_DIR, f);
    // never clobber a hand-authored (non-harness-shadow) user command of the same name
    if (existsSync(destPath) && !isHarnessShadow(destPath)) {
      skipped++;
      skippedNames.push(f.replace(/\.md$/, ""));
      continue;
    }
    if (!plan) {
      const body = readFileSync(resolve(SRC_DIR, f), "utf8").replace(/\n+$/, "");
      writeFileSync(destPath, withMarker(body) + "\n");
    }
    written++;
  }

  const tag = plan ? "shadow plan (dry-run)" : "shadow";
  ok(`${tag}: ${plan ? "would write" : "wrote"} ${written} bare /cmd → ${DEST_DIR}`);
  if (skipped) warn(`  skipped ${skipped} (hand-authored, not overwritten): ${skippedNames.join(" · ")}`);
  if (!plan) info("  reload Claude Code (/reload-plugins or restart) to pick up the bare commands");
  return 0;
}
